import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";
import { createLivingRealityProjection } from "../src/core/demo-projection.js";
import { LIVE_GATEWAY_SOURCE } from "../src/domains/live-gateway.js";
import { LIVE_GATEWAY_CONSOLE_SOURCE, createLiveGatewayConsole, summarizeLiveGateway } from "../src/render/live-gateway.js";

function makeElement(documentRoot, tag = "div") { return { ownerDocument: documentRoot, tagName: tag.toUpperCase(), id: "", className: "", dataset: {}, hidden: false, disabled: false, textContent: "", children: [], listeners: new Map(), attributes: new Map(), classList: { toggle() {} }, append(...children) { children.forEach((child) => this.appendChild(child)); }, appendChild(child) { this.children.push(child); return child; }, replaceChildren(...children) { this.children = children; }, addEventListener(type, callback) { this.listeners.set(type, callback); }, setAttribute(name, value) { this.attributes.set(name, String(value)); }, focus() {} }; }
function makeDocument() { const elements = new Map(); const documentRoot = { createElement(tag) { return makeElement(documentRoot, tag); }, getElementById(id) { return elements.get(id) ?? null; }, addEventListener() {} }; [["live-gateway-console", true], ["live-gateway-close"], ["live-gateway-replay"], ["live-gateway-reset"], ["live-gateway-status"], ["live-gateway-summary"], ["live-gateway-current"], ["live-gateway-evidence"], ["live-gateway-interpretations"], ["live-gateway-trace"], ["live-gateway-boundary"]].forEach(([id, hidden]) => { const element = makeElement(documentRoot); element.id = id; element.hidden = hidden === true; elements.set(id, element); }); return documentRoot; }

test("Live Gateway summary joins mock observation, uncertainty, and interpretation", () => { const summary = summarizeLiveGateway(createLivingRealityProjection().world); assert.equal(summary.source, LIVE_GATEWAY_SOURCE); assert.equal(summary.evidenceCount, 1); assert.equal(summary.interpretationCount, 1); assert.equal(summary.recordCount, 2); assert.equal(summary.evidence[0].uncertainty, 0.35); assert.equal(summary.interpretations[0].linkedEvidence[0].id, "gateway:evidence:demo"); assert.equal(summary.externalProviders, false); assert.equal(summary.providerCredentials, false); assert.equal(summary.truthClaim, false); assert.equal(summary.executable, false); assert.equal(Object.isFrozen(summary), true); });

test("Live Gateway console selects, replays, and resets without contacting providers", () => { const projection = createLivingRealityProjection().world; const before = JSON.stringify(projection); const callbacks = []; const adapter = createLiveGatewayConsole({ documentRoot: makeDocument(), projection, onSelect: (snapshot) => callbacks.push(snapshot), onReplay: (snapshot) => callbacks.push(snapshot), onReset: (snapshot) => callbacks.push(snapshot) }); const selected = adapter.selectInterpretation("gateway:interpretation:demo", "test"); assert.equal(selected.source, LIVE_GATEWAY_CONSOLE_SOURCE); assert.equal(selected.recordType, "interpretation"); assert.equal(selected.record.linkedEvidence[0].id, "gateway:evidence:demo"); const replay = adapter.replay("test"); assert.equal(replay.action, "replay"); assert.deepEqual(replay.sequence, ["observation", "uncertainty", "authority-boundary"]); assert.deepEqual(replay.linkedEvidenceIds, ["gateway:evidence:demo"]); adapter.reset("test"); assert.equal(adapter.getSnapshot().trace.length, 0); assert.equal(callbacks.map((item) => item.action).join(","), "select,replay,reset"); assert.equal(callbacks.every((item) => item.localOnly === true && item.simulation === true && item.executable === false), true); assert.equal(JSON.stringify(projection), before); });

test("Live Gateway console source exposes local provider boundary and no network path", async () => { const html = await readFile(new URL("../index.html", import.meta.url), "utf8"); const source = await readFile(new URL("../src/render/live-gateway.js", import.meta.url), "utf8"); for (const id of ["live-gateway-console", "live-gateway-close", "live-gateway-replay", "live-gateway-reset", "live-gateway-status", "live-gateway-summary", "live-gateway-current", "live-gateway-evidence", "live-gateway-interpretations", "live-gateway-trace", "live-gateway-boundary"]) { assert.match(html, new RegExp(`id=["']${id}["']`)); assert.match(source, new RegExp(id)); } assert.match(source, /function selectRecord\(/); assert.match(source, /function replay\(/); assert.doesNotMatch(source, /\bfetch\s*\(/i); assert.doesNotMatch(source, /new\s+WebSocket/i); assert.doesNotMatch(source, /navigator\.sendBeacon/i); });
