/* maTumbo Studio 0.6. Original MIT-licensed simulation utilities. */
(function(root){'use strict';
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function finite(x){if(!Number.isFinite(x))throw Error('Non-finite input');return x;}
function lightStats(pixels){if(!pixels||pixels.length<4||pixels.length%4)throw Error('Invalid RGBA sample');let sum=0,dark=0,bright=0;const n=pixels.length/4;for(let i=0;i<pixels.length;i+=4){const y=.2126*pixels[i]+.7152*pixels[i+1]+.0722*pixels[i+2];sum+=y;dark+=y<25;bright+=y>240;}return {mean:sum/n,dark:dark/n,bright:bright/n};}
class LightMeter{constructor(){this.mean=null;this.mode='normal';}update(stats){finite(stats.mean);this.mean=this.mean===null?stats.mean:.7*this.mean+.3*stats.mean;if(this.mode==='dim'&&this.mean>72)this.mode='normal';if(this.mode==='bright'&&this.mean<165)this.mode='normal';if(this.mean<48)this.mode='dim';else if(this.mean>190)this.mode='bright';return this.mode;}reset(){this.mean=null;this.mode='normal';}}
function planeRotate(q,count,dim,a,b,angle){if(!Number.isInteger(count)||count<1||q.length!==count*9||!Number.isInteger(dim)||dim<2||dim>9||!Number.isInteger(a)||!Number.isInteger(b)||a<0||b<0||a>=dim||b>=dim||a===b)throw Error('Choose two different active spatial axes');finite(angle);const c=Math.cos(angle),s=Math.sin(angle),out=Array.from(q);for(let i=0;i<count;i++){const x=finite(q[i*9+a]),y=finite(q[i*9+b]);out[i*9+a]=c*x-s*y;out[i*9+b]=s*x+c*y;}return out;}
function depthProxy(span,baseline){if(!Number.isFinite(span)||!Number.isFinite(baseline)||span<=.01||baseline<=.01)return 0;return clamp(Math.log(span/baseline)*1.4,-1.5,1.5);}
function recordingType(M){if(!M)return null;for(const t of ['video/webm;codecs=vp8','video/webm','video/mp4'])if(M.isTypeSupported(t))return t;return null;}
class HistoryTape{
 constructor({maxFrames=120,maxBytes=16*1024*1024}={}){this.maxFrames=maxFrames;this.maxBytes=maxBytes;this.frames=[];this.bytes=0;this.dropped=0;this.recording=false;this.started=0;this.revision=0;}
 start(now){finite(now);this.revision++;this.frames=[];this.bytes=0;this.dropped=0;this.started=now;this.recording=true;}
 add(snapshot,now){if(!this.recording)return false;finite(now);const t=now-this.started;if(t<0||this.frames.length&&t<=this.frames.at(-1).t)return false;const raw=JSON.stringify({t,state:snapshot}),size=raw.length*2;if(size>this.maxBytes)throw Error('Single checkpoint exceeds history budget');this.frames.push({t,state:JSON.parse(raw).state,size});this.bytes+=size;while(this.frames.length>this.maxFrames||this.bytes>this.maxBytes){this.bytes-=this.frames.shift().size;this.dropped++;}return true;}
 stop(){this.recording=false;}
 export(){return {format:'matumbo-history',version:1,sampling:'discrete checkpoints; no reconstructed intervals',cameraFrames:false,dropped:this.dropped,frames:this.frames.map(({t,state})=>({t,state}))};}
 async import(data,validate){if(this.recording)throw Error('Stop history capture before importing');if(!data||data.format!=='matumbo-history'||data.version!==1||data.cameraFrames!==false||!Array.isArray(data.frames)||!data.frames.length||data.frames.length>this.maxFrames)throw Error('Invalid history format or frame count');const revision=++this.revision,next=[];let bytes=0,prev=-1;for(let i=0;i<data.frames.length;i++){const f=data.frames[i];if(!Number.isFinite(f.t)||f.t<0||f.t<=prev||f.t>86400000)throw Error('Invalid checkpoint order');const raw=JSON.stringify({t:f.t,state:f.state}),size=raw.length*2;bytes+=size;if(bytes>this.maxBytes)throw Error('History exceeds memory budget');const value=JSON.parse(raw);await validate(value.state);next.push({...value,size});prev=f.t;if(i%8===0)await new Promise(r=>setTimeout(r,0));}if(this.recording||this.revision!==revision)throw Error('History changed during validation; import cancelled');this.frames=next;this.bytes=bytes;this.dropped=Number.isInteger(data.dropped)&&data.dropped>=0?data.dropped:0;}
}
const api={clamp,lightStats,LightMeter,planeRotate,depthProxy,recordingType,HistoryTape};root.FieldStudioCore=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
