/* maTumbo Field Studio 0.6: additive movement, preview lighting and explicit records.
 * No upload endpoint, microphone, background recording, or model retraining.
 * The underlying FieldApp owns simulation state. Camera overlay is not room AR.
 */
(function(){'use strict';
const A=window.FieldApp,C=window.FieldStudioCore;if(!A?.touchRepair||!C||A.studio)return;
const R=A.renderer,N=A.navigation,P=A.presence,T=A.touchRepair,X=A.xr,$=id=>document.getElementById(id);
const E=A.studio={version:'0.6.0',tape:new C.HistoryTape(),replay:false,live:null,lighting:'auto',effectiveLight:'normal',meter:new C.LightMeter(),lightSample:null,hold:null,video:null,videoBlob:null,includeCamera:false,depth:false,historyAt:0,lightAt:0,rotationAt:0,videoAt:0};
const html=`<div class="dialog-header"><h2>Field Studio · 0.6</h2><button id="studioClose">Close</button></div><div class="dialog-content">
<p id="studioMessage" role="status">Movement, light, and recorded history. Camera use stays optional.</p>
<h3>Move through the field</h3><button id="studioPadShow">Show movement pad over the field</button><p>Choose Grab node, Move field or View in the main toolbar. Hold an arrow below: it moves that object, the entire field, or your viewpoint. Near/far is actual simulated depth, not measured room depth.</p>
<div class="studio-grid"><button data-studio-move="0,0,1">Farther</button><button data-studio-move="0,1,0">Up</button><button data-studio-move="0,0,-1">Nearer</button><button data-studio-move="-1,0,0">Left</button><button data-studio-move="0,-1,0">Down</button><button data-studio-move="1,0,0">Right</button></div>
<label>Movement speed <input id="studioSpeed" type="range" min=".2" max="4" step=".1" value="1.2"></label>
<div class="studio-row"><label>Spatial axis <select id="studioAxis"></select></label><button id="studioMinus">− step</button><button id="studioPlus">+ step</button></div>
<label><input id="studioDepth" type="checkbox"> Approximate pinch depth from hand size</label><p class="studio-note">Opt-in camera gesture: move a held pinch toward/away from the lens. Hand size is an uncalibrated depth cue, not metres. Turn this off when tilting the hand causes unwanted depth motion.</p>
<div class="studio-row"><label>Rotate field in plane <select id="studioPlaneA"></select></label><select id="studioPlaneB" aria-label="Second rotation axis"></select><button id="studioRotate">Rotate 15°</button></div>
<p class="studio-note">These are spatial-axis operations. History below is time. No label claims extra physical dimensions have been discovered.</p>
<h3>Bright room / dark room</h3><label>Visibility <select id="studioLight"><option value="auto">Auto from camera preview</option><option value="bright">Bright room contrast</option><option value="dim">Dim room gentle display</option><option value="normal">Neutral</option></select></label><p id="studioLightState">Camera off · neutral view. Touch works without room light.</p><button id="studioTorch">Rear light: off / check support</button><p class="studio-note">Preview brightness is not a lux measurement or AR light estimation. A display filter cannot make an unlit hand visible to the camera. Use touch or provide light when tracking fails. Torch requires support from the selected camera.</p>
<h3>History: saved state, not a movie</h3><div class="studio-row"><button id="studioHistoryStart">Record history</button><button id="studioHistoryStop">Stop history</button><button id="studioHistorySave">Save JSON</button></div><p id="studioHistoryState">Not recording. Nothing captured automatically.</p><label>Recorded checkpoint <input id="studioTimeline" type="range" min="0" max="0" value="0" step="1" disabled></label><div class="studio-row"><button id="studioReturn">Return to live state</button><button id="studioImport">Load history JSON</button><button id="studioClear">Clear history</button></div><input id="studioHistoryFile" type="file" accept="application/json,.json" hidden><p class="studio-note">Up to 120 checkpoints at 2 per second; the 16 MB serialized-size budget can shorten that window (about 16 seconds for the default dense field). Scrubbing pauses and restores exact stored states, including observer and active/dormant axes. No camera images or hand landmarks enter history JSON. Return restores the pre-replay state, not a prediction. Camera must be restarted explicitly after replay.</p>
<h3>Video / still capture</h3><label><input type="checkbox" id="studioCameraConsent"> Include the currently active camera in the next video or still</label><p class="studio-note">Off by default. No audio. Camera imagery stays in the export until you choose to share it. Recording uses this scene composite, not other apps or the whole phone screen. Immersive Room AR camera capture is not supported here.</p><div class="studio-row"><button id="studioVideoStart">Record video</button><button id="studioVideoStop">Stop video</button><button id="studioVideoSave">Save video</button><button id="studioStill">Save PNG</button></div><p id="studioVideoState">Not recording. Video limit: 60 seconds or about 32 MB.</p><h3>Inspect performance</h3><p id="studioMetrics"></p><button id="studioReport">Save diagnostic report</button></div>`;
const style=document.createElement('style');style.textContent=`
#studioOpen{position:fixed;right:12px;top:96px;z-index:19;min-height:42px;padding:8px 13px;background:#10323a;color:#d9fff5;border:1px solid #8ad2c2;border-radius:12px;font:600 12px system-ui}
#studioDialog{width:min(590px,calc(100vw - 20px));max-height:88dvh}#studioDialog .dialog-content{font:13px/1.6 system-ui}#studioDialog button{min-height:44px;padding:7px 9px;font-size:12px}#studioDialog select{max-width:100%;background:#13333c;color:#eefff9;border:1px solid #64958e;padding:9px;border-radius:8px}#studioDialog label{display:block;margin:9px 0}#studioDialog input[type=range]{width:100%}.studio-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.studio-row{display:flex;gap:6px;flex-wrap:wrap;align-items:center}.studio-row>*{flex:1}.studio-note{font-size:11px;color:#a3c9ca}#studioMessage{padding:10px;border:1px solid #63968e;border-radius:8px}#studioLightState,#studioHistoryState,#studioVideoState{font-size:12px;overflow-wrap:anywhere}
#studioPad{position:fixed;right:12px;bottom:280px;width:175px;z-index:18;background:#0a2631ee;border:1px solid #78bbae;border-radius:14px;padding:8px}#studioPad[hidden]{display:none}#studioPad button{min-height:42px;font:11px system-ui;padding:4px}#studioPad select{width:100%;padding:6px;color:#d9fff5;background:#13333c;margin-bottom:6px}#studioPad .studio-grid{gap:4px}#studioPadClose{width:100%;margin-top:5px}.xr-running #studioPad{display:none}
#studioBadge{position:fixed;left:12px;top:103px;z-index:19;max-width:calc(100vw - 145px);font:600 10px system-ui;background:#08232beb;color:#cfffe6;border-radius:8px;padding:8px;pointer-events:none}.studio-replay #field,.studio-replay .touch-bar{pointer-events:none!important}.studio-replay #studioBadge{background:#452c11;color:#ffe0a1}
body[data-studio-light=bright] #cameraVideo{filter:brightness(.60) saturate(.8)}body[data-studio-light=bright] #touchObjects{filter:contrast(1.4)}body[data-studio-light=dim] #cameraVideo{filter:none}body[data-studio-light=dim] #field{opacity:.76}body[data-studio-light=dim] #touchObjects{opacity:.9}.xr-running #studioOpen,.xr-running #studioBadge{display:none}
@media(min-width:821px){#studioOpen{top:79px}#studioBadge{top:83px}}@media(max-height:600px){#studioOpen{top:70px}#studioBadge{top:73px}}`;
document.head.append(style);const dlg=document.createElement('dialog');dlg.id='studioDialog';dlg.innerHTML=html;document.body.append(dlg);const open=document.createElement('button');open.id='studioOpen';open.textContent='Move · Light · Record';document.body.append(open);const badge=document.createElement('div');badge.id='studioBadge';badge.textContent='STUDIO 0.6 · LIVE';document.body.append(badge);const pad=document.createElement('div');pad.id='studioPad';pad.hidden=true;pad.innerHTML='<select id="studioPadMode" aria-label="Movement target"><option value="grab">Move selected node</option><option value="field">Move whole field</option><option value="view">Move viewpoint</option></select><div class="studio-grid"><button data-studio-move="0,0,1">Farther</button><button data-studio-move="0,1,0">Up</button><button data-studio-move="0,0,-1">Nearer</button><button data-studio-move="-1,0,0">Left</button><button data-studio-move="0,-1,0">Down</button><button data-studio-move="1,0,0">Right</button></div><button id="studioPadClose">Hide pad</button>';document.body.append(pad);
function message(s){$('studioMessage').textContent=s;E.message=s;}
function release(){E.hold=null;T.release('Studio control');P.held=false;T.allowPinch=false;N.keys.clear();N.pointers.clear();}
function editable(){if(E.replay)throw Error('Return to live state before editing');if(X.active)throw Error('Use Room AR controls in the immersive session');}
function mutate(fn,type){editable();T.release('Movement control');const e=A.engine,before=e.energy();fn(e);e.work+=e.energy()-before;e.record({type});N.refresh();}
E.move=function(vector,amount){editable();if(!vector.every(Number.isFinite)||!Number.isFinite(amount))return;amount=C.clamp(amount,-.25,.25);if(T.mode==='view'){N.move(...vector,amount);return;}const dirs=NavMath.directions(R.camera),v=Array.from({length:3},(_,k)=>vector[0]*dirs.right[k]+vector[1]*dirs.up[k]+vector[2]*dirs.forward[k]);const delta=FieldTouchMath.lift(N.projectionBasis(),v,A.engine.activeDimensions),len=Math.hypot(...delta);if(len<1e-9)return;mutate(e=>{for(let i=0;i<e.count;i++)if(T.mode==='field'||i===R.selected)for(let d=0;d<e.activeDimensions;d++){e.q[i*9+d]+=delta[d]/len*amount;if(T.mode!=='field')e.velocity[i*9+d]=0;}},'studio-move');};
E.axis=function(axis,amount){if(!Number.isInteger(axis)||axis<0||axis>=A.engine.activeDimensions||!Number.isFinite(amount))throw Error('Choose an active spatial axis');if(T.mode==='view'){editable();N.origin[axis]=C.clamp(N.origin[axis]+amount,-200,200);N.follow=false;N.refresh();return;}mutate(e=>{for(let i=0;i<e.count;i++)if(T.mode==='field'||i===R.selected){e.q[i*9+axis]+=C.clamp(amount,-.5,.5);if(T.mode!=='field')e.velocity[i*9+axis]=0;}},'studio-axis-step');};
E.rotate=function(a,b,angle){mutate(e=>{e.q.set(C.planeRotate(e.q,e.count,e.activeDimensions,a,b,angle));e.velocity.set(C.planeRotate(e.velocity,e.count,e.activeDimensions,a,b,angle));},'studio-plane-rotation');};
const oldHand=P.consumeHand.bind(P);P.consumeHand=function(points){if(E.replay){this.lost();return;}oldHand(points);const d=T.drag;if(!E.depth||!d||d.source!=='hand'||!points||points.length!==21||d.dim<3)return;const aspect=(this.video.videoWidth||640)/(this.video.videoHeight||480),span=Math.hypot((points[5].x-points[17].x)*aspect,points[5].y-points[17].y);if(!Number.isFinite(span)||span<.01)return;if(!d.studioSpan)d.studioSpan=span;const depth=C.depthProxy(span,d.studioSpan),v=NavMath.directions(R.camera).forward.map(x=>-x*depth);try{const offset=FieldTouchMath.lift(d.b,v,d.dim);d.delta=d.delta.map((x,k)=>x+offset[k]);}catch(_){release();}};
function updateAxes(){const count=A.engine.activeDimensions;for(const id of ['studioAxis','studioPlaneA','studioPlaneB']){const el=$(id),prev=+el.value;if(el.options.length===count)continue;el.replaceChildren(...Array.from({length:count},(_,i)=>new Option('x'+(i+1),i)));el.value=String(id==='studioPlaneB'?Math.min(count-1,Math.max(1,prev)):Math.min(count-1,prev));}}
function applyLight(mode){E.effectiveLight=mode;document.body.dataset.studioLight=mode;}
E.updateLight=function(stats){E.lightSample=stats;const auto=E.meter.update(stats);applyLight(E.lighting==='auto'?auto:E.lighting);const risk=stats.dark>.6?'Very little camera detail: use touch or add light.':stats.bright>.35?'Highlights clipped: avoid pointing directly at a light.':'Preview has usable tonal range; this is not a tracking guarantee.';$('studioLightState').textContent=E.effectiveLight.toUpperCase()+' · preview '+Math.round(E.meter.mean)+'/255 · '+risk;};
const lightCanvas=document.createElement('canvas');lightCanvas.width=32;lightCanvas.height=24;const lightCtx=lightCanvas.getContext('2d',{willReadFrequently:true});
function sampleLight(){if(!P.stream||P.video.readyState<2){if(E.lighting==='auto'){E.meter.reset();applyLight('normal');}$('studioLightState').textContent='Camera off · '+E.effectiveLight+' display. Touch remains available.';return;}try{lightCtx.drawImage(P.video,0,0,32,24);E.updateLight(C.lightStats(lightCtx.getImageData(0,0,32,24).data));}catch(e){$('studioLightState').textContent='Brightness sample unavailable. Manual visibility modes still work.';}}
E.torch=async function(){const track=P.stream?.getVideoTracks()[0],caps=track?.getCapabilities?.();if(!track||!caps?.torch)throw Error('Selected camera does not expose torch control');await track.applyConstraints({advanced:[{torch:!track.getSettings().torch}]});$('studioTorch').textContent='Rear light: '+(track.getSettings().torch?'on':'off');};
function historyUI(){const tape=E.tape;const n=tape.frames.length;$('studioTimeline').max=String(Math.max(0,n-1));$('studioTimeline').disabled=n===0||tape.recording;$('studioHistoryState').textContent=(tape.recording?'RECORDING HISTORY · ':E.replay?'RECORDED PAST · ':'History stopped · ')+n+' checkpoints · '+(tape.bytes/1048576).toFixed(1)+' MB'+(tape.dropped?' · oldest checkpoints discarded':'');badge.textContent=E.replay?'RECORDED PAST · READ ONLY':E.video?'● VIDEO RECORDING':tape.recording?'● HISTORY RECORDING':'STUDIO 0.6 · LIVE';}
E.startHistory=function(){editable();if(E.tape.recording)throw Error('History capture already running');if(E.tape.frames.length)throw Error('Save or clear the existing history before a new capture');release();E.tape.start(performance.now());E.historyAt=performance.now();E.tape.add(A.snapshot(),E.historyAt);historyUI();};
E.stopHistory=function(){if(E.tape.recording){try{E.tape.add(A.snapshot(),performance.now());}catch(e){message(e.message);}finally{E.tape.stop();}}historyUI();};
E.seek=async function(index){if(E.tape.recording)throw Error('Stop history recording before scrubbing');if(!Number.isInteger(index)||!E.tape.frames[index])throw Error('Choose a recorded checkpoint');if(E.video)throw Error('Stop video before replay');if(X.active||X.pending)throw Error('Exit Room AR before replay');if(!E.replay){release();E.live=A.snapshot();E.replay=true;document.body.classList.add('studio-replay');}A.applySnapshot(E.tape.frames[index].state,false);A.setPause(true);N.refresh();$('studioTimeline').value=String(index);historyUI();message('Checkpoint '+(index+1)+' · recorded '+(E.tape.frames[index].t/1000).toFixed(2)+' s · simulation tick '+A.engine.tick+'. Not interpolated or predicted.');};
E.returnLive=function(){if(!E.replay)return;const live=E.live;E.replay=false;E.live=null;document.body.classList.remove('studio-replay');A.applySnapshot(live,false);historyUI();message('Live state restored exactly. Camera stays off until you start it.');};
function validateState(s){if(s?.format!=='matumbo-field-lab'||s.version!==2)throw Error('Unsupported state');const e=NDPhysics.NDFieldEngine.restore(s.engine),v=s.view;if(!v||!Number.isInteger(v.dimensions)||v.dimensions<2||v.dimensions>9||!['field','network','memory'].includes(v.mode)||!['light','balanced','ultra'].includes(v.quality)||!NavMath.validCamera(v.camera)||!Number.isInteger(v.selected)||v.selected<0||v.selected>=e.count||typeof v.paused!=='boolean'||typeof v.autoOrbit!=='boolean'||!['2','3','all'].includes(v.spatialLens))throw Error('Invalid saved view');NavMath.validateState(v.navigation,e.activeDimensions,e.count);if(!Array.isArray(s.landmarks)||s.landmarks.length>30)throw Error('Invalid landmarks');const used=new Set();for(const l of s.landmarks){if(!Number.isInteger(l.node)||l.node<0||l.node>=e.count||used.has(l.node)||typeof l.name!=='string'||!l.name.trim()||l.name.length>32)throw Error('Invalid landmark');used.add(l.node);}}
E.importHistory=async function(data){if(E.replay)throw Error('Return to live before importing');if(E.tape.frames.length)throw Error('Save or clear the existing history before importing');await E.tape.import(data,validateState);historyUI();};
const composite=document.createElement('canvas'),ctx=composite.getContext('2d');
function compose(includeCamera){if(X.active||X.pending)throw Error('Scene recording is unavailable inside immersive Room AR');const scale=Math.min(1,720/R.width,1280/R.height),w=Math.max(2,Math.floor(R.width*scale/2)*2),h=Math.max(2,Math.floor(R.height*scale/2)*2);if(composite.width!==w||composite.height!==h){composite.width=w;composite.height=h;}ctx.setTransform(1,0,0,1,0,0);ctx.globalAlpha=1;ctx.filter='none';ctx.fillStyle='#07131c';ctx.fillRect(0,0,w,h);if(includeCamera){if(!P.stream||P.video.readyState<2)throw Error('Start camera explicitly before including it');const vw=P.video.videoWidth,vh=P.video.videoHeight,k=Math.max(w/vw,h/vh),ox=(w-vw*k)/2,oy=(h-vh*k)/2;ctx.save();if(P.actualFacing==='user'){ctx.translate(w,0);ctx.scale(-1,1);}if(E.effectiveLight==='bright')ctx.filter='brightness(60%) saturate(80%)';ctx.drawImage(P.video,ox,oy,vw*k,vh*k);ctx.restore();}ctx.globalAlpha=E.effectiveLight==='dim'?.76:1;ctx.drawImage(R.canvas,0,0,w,h);ctx.globalAlpha=1;ctx.drawImage(T.canvas,0,0,w,h);if(includeCamera&&P.canvas)ctx.drawImage(P.canvas,0,0,w,h);ctx.fillStyle='#06151be6';ctx.fillRect(0,h-31,w,31);ctx.fillStyle='#caffeb';ctx.font='11px system-ui';ctx.fillText('maTumbo · '+(E.replay?'RECORDED PAST':includeCamera?'CAMERA OVERLAY':'SIMULATION')+' · tick '+A.engine.tick,10,h-11);return composite;}
E.compose=compose;
E.startVideo=function(includeCamera=false){editable();if(E.video)throw Error('Video already recording or finishing');if(E.videoBlob)throw Error('Save or discard the previous video before recording again');const type=C.recordingType(window.MediaRecorder);if(!type||!composite.captureStream)throw Error('This browser cannot record this canvas. PNG and JSON still work.');compose(includeCamera);const stream=composite.captureStream(24);let recorder;try{recorder=new MediaRecorder(stream,{mimeType:type,videoBitsPerSecond:2500000});}catch(e){stream.getTracks().forEach(t=>t.stop());throw e;}const record={recorder,stream,chunks:[],bytes:0,started:performance.now(),includeCamera,stopping:false};E.video=record;recorder.ondataavailable=e=>{if(e.data.size){record.chunks.push(e.data);record.bytes+=e.data.size;if(record.bytes>=32*1024*1024)E.stopVideo('Size limit reached');}};recorder.onerror=()=>{message('Video encoder error. Any completed chunks can still be saved.');E.stopVideo('Encoder error');};recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());E.videoBlob=new Blob(record.chunks,{type:recorder.mimeType||type});E.video=null;$('studioVideoState').textContent='Stopped · '+(E.videoBlob.size/1048576).toFixed(2)+' MB · Save video, then discard before a new recording.';historyUI();};try{recorder.start(1000);}catch(e){E.video=null;stream.getTracks().forEach(t=>t.stop());throw e;}$('studioVideoState').textContent='RECORDING · '+(includeCamera?'includes your camera':'field only')+' · no audio';historyUI();};
E.stopVideo=function(reason='Stopped'){const v=E.video;if(!v||v.stopping)return;v.stopping=true;if(v.recorder.state!=='inactive')v.recorder.stop();$('studioVideoState').textContent=reason+' · finishing file…';};
function download(name,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function action(fn){return async()=>{try{await fn();}catch(e){message(e.message);}};}
$('studioPadShow').onclick=()=>{release();$('studioPadMode').value=T.mode;pad.hidden=false;dlg.close();};$('studioPadClose').onclick=()=>{release();pad.hidden=true;};$('studioPadMode').onchange=()=>{release();$({grab:'touchGrab',field:'touchField',view:'touchView'}[$('studioPadMode').value]).click();};
$('studioOpen').onclick=()=>{release();updateAxes();dlg.showModal();};$('studioClose').onclick=()=>dlg.close();dlg.addEventListener('close',()=>release());
for(const button of document.querySelectorAll('[data-studio-move]')){button.onpointerdown=e=>{e.preventDefault();release();button.setPointerCapture(e.pointerId);E.hold=button.dataset.studioMove.split(',').map(Number);};for(const ev of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(ev,()=>E.hold=null);}
$('studioMinus').onclick=action(()=>E.axis(+$('studioAxis').value,-.2));$('studioPlus').onclick=action(()=>E.axis(+$('studioAxis').value,.2));$('studioRotate').onclick=action(()=>E.rotate(+$('studioPlaneA').value,+$('studioPlaneB').value,Math.PI/12));$('studioDepth').onchange=()=>{release();E.depth=$('studioDepth').checked;};$('studioLight').onchange=()=>{E.lighting=$('studioLight').value;applyLight(E.lighting==='auto'?E.meter.mode:E.lighting);sampleLight();};$('studioTorch').onclick=action(()=>E.torch());
$('studioHistoryStart').onclick=action(()=>E.startHistory());$('studioHistoryStop').onclick=()=>E.stopHistory();$('studioTimeline').oninput=action(()=>E.seek(+$('studioTimeline').value));$('studioReturn').onclick=action(()=>E.returnLive());$('studioHistorySave').onclick=action(()=>{if(!E.tape.frames.length)throw Error('No history recorded');download('matumbo-history.json',new Blob([JSON.stringify(E.tape.export())],{type:'application/json'}));});$('studioClear').onclick=action(()=>{if(E.replay)throw Error('Return to live before clearing');if(E.tape.recording)throw Error('Stop history capture first');if(E.tape.frames.length&&!confirm('Discard recorded history from this session? Save JSON first to keep it.'))return;E.tape=new C.HistoryTape();historyUI();});$('studioImport').onclick=()=>{$('studioHistoryFile').click();};$('studioHistoryFile').onchange=action(async()=>{const file=$('studioHistoryFile').files[0];if(!file)return;try{if(file.size>16*1024*1024)throw Error('History JSON exceeds 16 MB');await E.importHistory(JSON.parse(await file.text()));message('History validated and loaded. Live state unchanged.');}finally{$('studioHistoryFile').value='';}});
$('studioCameraConsent').onchange=()=>{if(E.video){E.stopVideo('Capture consent changed');message('Recording stopped. Start another recording to use the changed camera choice.');}};$('studioVideoStart').onclick=action(()=>E.startVideo($('studioCameraConsent').checked));$('studioVideoStop').onclick=()=>E.stopVideo();$('studioVideoSave').onclick=action(()=>{if(!E.videoBlob?.size)throw Error('Stop a video recording before saving');download('matumbo-recording.'+(E.videoBlob.type.includes('mp4')?'mp4':'webm'),E.videoBlob);});const discard=document.createElement('button');discard.textContent='Discard saved video buffer';discard.onclick=()=>{if(E.videoBlob&&confirm('Discard this video buffer? Save the video first to keep it.')){E.videoBlob=null;$('studioVideoState').textContent='Video buffer discarded. Nothing recording.';}};$('studioVideoState').after(discard);$('studioStill').onclick=action(()=>{const canvas=compose($('studioCameraConsent').checked);canvas.toBlob(blob=>{if(blob)download('matumbo-still.png',blob);else message('PNG encoding failed');},'image/png');});$('studioReport').onclick=()=>P.exportDiagnostics();
// Read-only replay gates original input without replacing the engine or its APIs.
const oldPause=A.setPause;A.setPause=v=>{if(E.replay&&!v)return;oldPause(v);};document.addEventListener('click',e=>{if(E.replay&&!e.target.closest('#studioDialog,#studioOpen')){e.stopImmediatePropagation();e.preventDefault();}},true);document.addEventListener('keydown',e=>{if(E.replay&&!e.target.closest('#studioDialog')){e.stopImmediatePropagation();e.preventDefault();}},true);
const oldPointer=N.handlePointer.bind(N);N.handlePointer=e=>{if(E.replay){release();return;}return oldPointer(e);};const oldBefore=N.beforeFrame.bind(N);N.beforeFrame=function(dt){if(E.replay){N.keys.clear();return;}oldBefore(dt);if(E.hold&&!document.hidden)try{E.move(E.hold,Math.min(dt,.04)*+$('studioSpeed').value);}catch(e){E.hold=null;message(e.message);}};
const oldRender=R.render.bind(R);R.render=function(dt){if(E.replay)oldPause(true);oldRender(dt);const now=performance.now();if(now-E.lightAt>500){E.lightAt=now;sampleLight();updateAxes();$('studioMetrics').textContent='Mode: '+T.mode+' · '+Math.round(1000/Math.max(1,T.frameMs))+' FPS · hand result age '+Math.round(T.roundTrip||0)+' ms · '+T.backend+' · '+E.effectiveLight+' visibility';}if(E.tape.recording&&now-E.historyAt>=500){E.historyAt=now;try{E.tape.add(A.snapshot(),now);historyUI();}catch(e){E.stopHistory();message(e.message);}}if(E.video&&!E.video.stopping&&now-E.videoAt>=1000/24){E.videoAt=now;try{compose(E.video.includeCamera);if(now-E.video.started>=60000)E.stopVideo('60 second limit');}catch(e){E.stopVideo(e.message);}}};
const oldXRFrame=X.frame.bind(X);X.frame=function(now,frame){if(E.video)E.stopVideo('Entering Room AR');oldXRFrame(now,frame);if(E.tape.recording&&now-E.historyAt>=500){E.historyAt=now;try{E.tape.add(A.snapshot(),now);historyUI();}catch(e){E.stopHistory();message(e.message);}}};
window.addEventListener('resize',()=>{E.hold=null;if(E.video)E.stopVideo('View size changed; start a new recording');});
const oldStop=P.stop.bind(P);P.stop=function(s){if(E.video?.includeCamera)E.stopVideo('Camera stopped');E.meter.reset();return oldStop(s||'Camera stopped. Explicit Studio recordings remain available.');};
const oldDiagnostics=P.diagnostics.bind(P);P.diagnostics=function(){const out=oldDiagnostics();out.studio={version:E.version,lighting:E.lighting,effectiveLighting:E.effectiveLight,previewStats:E.lightSample,approximateDepth:E.depth,historyFrames:E.tape.frames.length,historyBytes:E.tape.bytes,historyRecording:E.tape.recording,replay:E.replay,videoRecording:!!E.video,videoIncludesCamera:E.video?.includeCamera||false};$('diagnosticsText').textContent=JSON.stringify(out,null,2);return out;};
for(const event of ['pagehide','blur'])window.addEventListener(event,()=>{release();E.stopHistory();E.stopVideo('App hidden or focus lost');});document.addEventListener('visibilitychange',()=>{if(document.hidden){release();E.stopHistory();E.stopVideo('Tab hidden');}});document.title='maTumbo Field Studio 0.6 · Move, Light, Record';updateAxes();historyUI();applyLight('normal');
})();
