/* Viva 0.7. Pure, bounded geometry and visibility helpers. MIT.
 * Circuit: fixed classical order-nine 33x32 topology; not a general mesher.
 * Brightness estimates are image statistics, never lux or tracking confidence.
 */
(function(root){'use strict';
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const clone=x=>JSON.parse(JSON.stringify(x));
const finite=(x,bound=1e6)=>typeof x==='number'&&Number.isFinite(x)&&Math.abs(x)<=bound;
const EDGES=[['S1','T','C','L','M'],['S2','T','B','M','R'],['S3','B','D','M','N'],['S4','B','E','N','R'],['S5','C','Z','L','O'],['S6','C','D','O','M'],['S7','D','Z','O','P'],['S8','D','E','P','N'],['S9','E','Z','P','R']];
function solve(a,b){const n=b.length;if(!n||a.length!==n||a.some(r=>r.length!==n))throw Error('Invalid linear system');const m=a.map((r,i)=>[...r,b[i]]);if(m.flat().some(x=>!finite(x)))throw Error('Invalid coefficient');for(let j=0;j<n;j++){let p=j;for(let i=j+1;i<n;i++)if(Math.abs(m[i][j])>Math.abs(m[p][j]))p=i;if(Math.abs(m[p][j])<1e-12)throw Error('Singular circuit');[m[j],m[p]]=[m[p],m[j]];const d=m[j][j];for(let k=j;k<=n;k++)m[j][k]/=d;for(let i=0;i<n;i++)if(i!==j){const f=m[i][j];for(let k=j;k<=n;k++)m[i][k]-=f*m[j][k];}}return m.map(r=>r[n]);}
function dirichlet(edges,boundary){const unknown=[...new Set(edges.flat())].filter(v=>!(v in boundary)).sort(),a=unknown.map(()=>unknown.map(()=>0)),b=unknown.map(()=>0);unknown.forEach((v,i)=>{for(const [p,q]of edges)if(v===p||v===q){const w=v===p?q:p,j=unknown.indexOf(w);a[i][i]++;if(j<0)b[i]+=boundary[w];else a[i][j]--;}});const solution=solve(a,b);return Object.assign({},boundary,Object.fromEntries(unknown.map((v,i)=>[v,solution[i]])));}
function circuit(height=32){if(!finite(height,100)||height<=0)throw Error('Height must be in (0,100]');const primal=EDGES.map(e=>e.slice(1,3)),dual=EDGES.map(e=>e.slice(3,5)),v=dirichlet(primal,{T:height,Z:0}),width=EDGES.filter(e=>e[1]==='T').reduce((s,e)=>s+v[e[1]]-v[e[2]],0),x=dirichlet(dual,{L:0,R:width});const tiles=EDGES.map(([id,t,b,l,r])=>({id,x:x[l],y:height-v[t],width:x[r]-x[l],height:v[t]-v[b]}));const residual=Math.max(...Object.keys(v).filter(k=>!['T','Z'].includes(k)).map(k=>Math.abs(primal.reduce((s,[a,b])=>s+(a===k?v[k]-v[b]:b===k?v[k]-v[a]:0),0))));const out={height,width,voltage:v,tiles,residual};checkCircuit(out);return out;}
function checkCircuit(c){const t=c.tiles,eps=1e-7;if(!Array.isArray(t)||t.length!==9||!finite(c.width)||!finite(c.height)||c.width<=0||c.height<=0)throw Error('Invalid circuit tiling');let area=0;for(let i=0;i<t.length;i++){const a=t[i];if(![a.x,a.y,a.width,a.height].every(x=>finite(x))||a.width<=0||Math.abs(a.width-a.height)>eps||a.x< -eps||a.y< -eps||a.x+a.width>c.width+eps||a.y+a.height>c.height+eps)throw Error('Invalid square');area+=a.width*a.height;for(let j=0;j<i;j++){const b=t[j],dx=Math.min(a.x+a.width,b.x+b.width)-Math.max(a.x,b.x),dy=Math.min(a.y+a.height,b.y+b.height)-Math.max(a.y,b.y);if(dx>eps&&dy>eps)throw Error('Overlapping tiles');if(Math.abs(a.width-b.width)<eps)throw Error('Repeated square size');}}if(Math.abs(area-c.width*c.height)>eps)throw Error('Incomplete coverage');return true;}
function imageStats(data,width,height,roi=null){if(!(data instanceof Uint8Array||data instanceof Uint8ClampedArray)||!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1||data?.length!==width*height*4||width*height>1048576)throw Error('Invalid image sample');let x0=0,y0=0,x1=width,y1=height;if(roi){if(!Array.isArray(roi)||roi.length!==4||roi.some(x=>!finite(x,10)))throw Error('Invalid region');x0=clamp(Math.floor(roi[0]*width),0,width-1);y0=clamp(Math.floor(roi[1]*height),0,height-1);x1=clamp(Math.ceil(roi[2]*width),x0+1,width);y1=clamp(Math.ceil(roi[3]*height),y0+1,height);}const hist=new Uint32Array(256);let sum=0,sq=0,n=0,black=0,white=0;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){const i=(y*width+x)*4,l=Math.round(.2126*data[i]+.7152*data[i+1]+.0722*data[i+2]);hist[l]++;sum+=l;sq+=l*l;n++;black+=l<=12;white+=l>=248;}const quantile=q=>{let s=0;for(let i=0;i<256;i++){s+=hist[i];if(s>=q*n)return i;}return 255;};return{mean:sum/n,sd:Math.sqrt(Math.max(0,sq/n-(sum/n)**2)),dark:black/n,clipped:white/n,p10:quantile(.1),p90:quantile(.9),pixels:n};}
function lightClass(s){if(!s||!finite(s.mean,255)||!finite(s.dark,1)||!finite(s.clipped,1))throw Error('Invalid lighting statistics');if(s.mean<24||s.dark>.83)return 'dark';if(s.clipped>.28||s.mean>207)return 'glare';return 'balanced';}
class LightGuard{constructor(){this.mode='balanced';this.candidate='balanced';this.count=0;}update(s){const next=lightClass(s);if(next===this.candidate)this.count++;else{this.candidate=next;this.count=1;}if(this.count>=3||s.mean<4||s.clipped>.97)this.mode=next;return this.mode;}}
function handRegion(points){if(!Array.isArray(points)||points.length!==21||points.some(p=>!p||!finite(p.x,3)||!finite(p.y,3)))return null;const xs=points.map(p=>p.x),ys=points.map(p=>p.y);return [clamp(Math.min(...xs)-.03,0,1),clamp(Math.min(...ys)-.03,0,1),clamp(Math.max(...xs)+.03,0,1),clamp(Math.max(...ys)+.03,0,1)];}
class HandGate{
 constructor(){this.reset();}
 reset(){this.ready=false;this.openFrames=0;this.reason='Show an open hand';this.previousTime=null;}
 accept({points,now,age=0,ratio,open=.42,stats=null}){if(!finite(now,1e15)||!finite(age)||age<0||age>240||!handRegion(points)||!finite(ratio,20)){this.reset();this.reason=age>240?'Late hand result':'Hand unavailable';return false;}if(this.previousTime!==null&&(now<=this.previousTime||now-this.previousTime>350)){this.reset();}this.previousTime=now;if(stats&&(stats.mean<12||stats.dark>.94||stats.clipped>.9)){this.reset();this.reason=stats.clipped>.9?'Hand image overexposed':'Not enough hand detail';return false;}if(!this.ready){if(ratio>open)this.openFrames++;else this.openFrames=0;this.ready=this.openFrames>=3;this.reason=this.ready?'Hand ready':'Open hand to re-arm';return this.ready;}this.reason='Hand ready';return true;}
}
// No dynamic code, arbitrary URLs, or names as property keys are accepted.
const IDS=['field','circuit',...EDGES.map(e=>'room-'+e[0]),'inner-lab'];
function route(id){if(id==='field')return[];if(id==='circuit')return['field'];if(id==='inner-lab')return['field','circuit','room-S1'];if(IDS.includes(id))return['field','circuit'];throw Error('Unknown space');}
function validMeta(m){return !!m&&m.version===1&&IDS.includes(m.space)&&Array.isArray(m.path)&&JSON.stringify(m.path)===JSON.stringify(route(m.space));}
function validateUniverse(data,validateState){if(!data||data.format!=='matumbo-viva-universe'||data.version!==1||!IDS.includes(data.active)||!Array.isArray(data.worlds)||data.worlds.length<1||data.worlds.length>IDS.length||JSON.stringify(data.path)!==JSON.stringify(route(data.active)))throw Error('Invalid universe header');const next=new Map();for(const w of data.worlds){if(!w||!IDS.includes(w.id)||next.has(w.id)||typeof w.name!=='string'||w.name.length>48||!Number.isSafeInteger(w.revision)||w.revision<0)throw Error('Invalid world');validateState(w.state);if(w.state.viva&&!validMeta(w.state.viva))throw Error('Invalid world metadata');if(w.state.viva&&w.state.viva.space!==w.id)throw Error('World identity mismatch');next.set(w.id,clone(w));}if(!next.has('field')||!next.has(data.active))throw Error('Missing current or root world');return next;}
function boundedEvents(events){if(!Array.isArray(events)||events.length>600)throw Error('Invalid event journal');let previous=-1;return events.map(e=>{if(!e||!Number.isSafeInteger(e.sequence)||e.sequence<=previous||!IDS.includes(e.space)||!['enter','leave','grab','move','save','resume'].includes(e.type))throw Error('Invalid recorded event');previous=e.sequence;return{sequence:e.sequence,space:e.space,type:e.type};});}
const api={clamp,clone,finite,EDGES,IDS,solve,circuit,checkCircuit,imageStats,lightClass,LightGuard,handRegion,HandGate,route,validMeta,validateUniverse,boundedEvents};root.VivaCore=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
