/* Viva 0.7: persistent mapped spaces, circuit overview and explicit entry.
 * Extends the canonical FieldApp. Interiors use the same NDFieldEngine.
 * Exterior miniatures are mapped representations, not AR depth/occlusion.
 */
(function(){'use strict';
const A=window.FieldApp,C=window.VivaCore;if(!A?.studio||!C||A.viva)return;
const R=A.renderer,N=A.navigation,P=A.presence,T=A.touchRepair,E=A.studio,$=id=>document.getElementById(id),copy=C.clone;
const baseSnapshot=A.snapshot.bind(A),baseApply=A.applySnapshot.bind(A),baseStop=P.stop.bind(P);
const U=A.viva={version:'0.7.0',active:'field',worlds:new Map(),path:[],journal:[],sequence:0,transition:false,importing:false,dirty:false,saving:false,circuit:C.circuit(),selection:0,preview:null,captureDraws:0,focus:true};
const names={field:'Original Field',circuit:'Circuit Atrium','inner-lab':'Inner Workshop'};for(let i=1;i<=9;i++)names['room-S'+i]=['Echo Garden','Signal Hall','Wave Chamber','Memory Room','Resonance Court','Pattern Vault','Observer Room','Quiet Cell','Harmonic Hall'][i-1];
function meta(id=U.active){return{version:1,space:id,path:C.route(id)};}
function tell(text){const m=$('vivaMessage');m.textContent=text;U.message=text;if(U.focus&&U.active!=='field'){m.style.setProperty('display','block','important');m.style.top='auto';m.style.bottom='108px';}else{m.style.removeProperty('display');m.style.removeProperty('top');m.style.removeProperty('bottom');}}
function release(){T.release('Space transition');P.lost();N.keys.clear();N.pointers.clear();E.hold=null;R.autoOrbit=false;}
function editable(){if(E.replay)throw Error('Return to live history before changing worlds.');if(U.importing)throw Error('Universe validation is still running.');if(A.xr.active||A.xr.pending)throw Error('Exit Room AR before entering a mapped space. Room AR still uses the original placed field.');}
function event(type){U.journal.push({sequence:++U.sequence,space:U.active,type});if(U.journal.length>600)U.journal.shift();U.dirty=true;}
function stateNow(){const s=baseSnapshot();s.viva=meta();return s;}
function stash(){const old=U.worlds.get(U.active);U.worlds.set(U.active,{id:U.active,name:names[U.active],revision:(old?.revision||0)+1,state:stateNow()});}
function validateState(s){if(s?.format!=='matumbo-field-lab'||s.version!==2)throw Error('Invalid field snapshot');const e=NDPhysics.NDFieldEngine.restore(s.engine),v=s.view;if(!v||!Number.isInteger(v.dimensions)||v.dimensions<2||v.dimensions>9||!['field','network','memory'].includes(v.mode)||!['light','balanced','ultra'].includes(v.quality)||!['all','2','3'].includes(v.spatialLens)||!NavMath.validCamera(v.camera)||!Number.isInteger(v.selected)||v.selected<0||v.selected>=e.count||typeof v.paused!=='boolean'||typeof v.autoOrbit!=='boolean')throw Error('Invalid observer');NavMath.validateState(v.navigation,e.activeDimensions,e.count);if(!Array.isArray(s.landmarks)||s.landmarks.length>30)throw Error('Invalid object labels');const used=new Set();for(const l of s.landmarks){if(!Number.isInteger(l.node)||l.node<0||l.node>=e.count||used.has(l.node)||typeof l.name!=='string'||!l.name.trim()||l.name.length>32)throw Error('Invalid object label');used.add(l.node);}if(s.viva&&!C.validMeta(s.viva))throw Error('Invalid space frame');return true;}
U.validateState=validateState;
function makeWorld(id){if(!C.IDS.includes(id)||id==='field')throw Error('Unknown destination');const e=new NDPhysics.NDFieldEngine({count:24,seed:730+C.IDS.indexOf(id),activeDimensions:3});e.q.fill(0);e.velocity.fill(0);for(let i=0;i<24;i++){e.q[i*9]=Math.sin(i*2.4)*3.2;e.q[i*9+1]=.3+(i%4)*.2;e.q[i*9+2]=Math.cos(i*2.4)*2.8;for(let d=3;d<9;d++)e.q[i*9+d]=Math.sin(i+d)*.25;}let labels;
 if(id==='circuit'){labels=U.circuit.tiles.map((tile,i)=>{e.q[i*9]=(tile.x+tile.width/2-U.circuit.width/2)/3;e.q[i*9+1]=.1;e.q[i*9+2]=(tile.y+tile.height/2-U.circuit.height/2)/3;return{node:i,name:tile.id+' · '+names['room-'+tile.id].slice(0,20),kind:'MAPPED ENTRANCE'};});}
 else{const p=[[-1.6,.05,1.2],[1.6,.35,.4],[0,.5,-2.5],[-.4,.15,2.6]];p.forEach((q,i)=>e.q.set(q,i*9));labels=[{node:0,name:'Relic',kind:'PERSISTENT OBJECT'},{node:1,name:'Signal',kind:'PERSISTENT OBJECT'},{node:2,name:id==='room-S1'?'Inner Workshop':'Resonator',kind:id==='room-S1'?'MAPPED ENTRANCE':'PERSISTENT OBJECT'},{node:3,name:'Echo',kind:'PERSISTENT OBJECT'}];}
 e.rebuildTopology();e.params={coupling:1.2,damping:.35,drive:.15,plasticity:false};e.work=0;e.dissipated=0;e.initialEnergy=e.energy();e.branch='viva/'+id;const s=baseSnapshot();s.engine=e.snapshot();s.landmarks=labels;s.view={...s.view,dimensions:3,spatialLens:'all',mode:'network',quality:'light',selected:0,paused:true,autoOrbit:false,camera:{target:[0,0,0],yaw:id==='circuit'?.12:.12,pitch:id==='circuit'?.95:.33,distance:id==='circuit'?(R.width<600?28:17):13},navigation:{...s.view.navigation,mode:'orbit',origin:Array(9).fill(0),axes:[0,1,2],custom:true,slice:false,follow:false,isolate:false,path:[]}};s.viva=meta(id);validateState(s);return{id,name:names[id],revision:0,state:s};}
const templates=new Map();function obtain(id){if(U.worlds.has(id))return U.worlds.get(id);if(!templates.has(id))templates.set(id,makeWorld(id));return templates.get(id);}
A.snapshot=function(){return stateNow();};
// Ordinary state loads and history always keep explicit observer-space metadata.
A.applySnapshot=function(s,clear=true){validateState(s);const id=s.viva?.space||'field';baseApply(s,clear);U.active=id;U.path=C.route(id);refresh();};
P.stop=function(message){if(U.transition&&message===undefined)return;return baseStop(message);};
function switchTo(id,type){editable();if(U.active===id)return;release();const candidate=obtain(id);validateState(candidate.state);const oldActive=U.active,old=stateNow();stash();U.transition=true;try{baseApply(candidate.state,true);U.active=id;U.path=C.route(id);U.worlds.set(id,candidate);N.refresh();}catch(error){baseApply(old,false);U.active=oldActive;U.path=C.route(oldActive);throw error;}finally{U.transition=false;}P.lost();event(type);refresh();if(E.tape.recording)E.tape.add(A.snapshot(),performance.now());tell('Inside '+names[id]+'. Touch a solid handle to move it. Exit preserves its state.');}
U.enter=function(id){const allowed=U.active==='field'?['circuit']:U.active==='circuit'?C.EDGES.map(e=>'room-'+e[0]):U.active==='room-S1'?['inner-lab']:[];if(!allowed.includes(id))throw Error('No entrance to that space from here.');switchTo(id,'enter');};
U.back=function(){editable();const parent=C.route(U.active).at(-1);if(parent)switchTo(parent,'leave');};
U.enterSelected=function(){if(U.active==='field')return U.enter('circuit');if(U.active==='circuit'&&R.selected<9)return U.enter('room-S'+(R.selected+1));if(U.active==='room-S1'&&R.selected===2)return U.enter('inner-lab');tell('This object is not an entrance. Grab and move it instead.');};
U.export=function(){editable();stash();const data={format:'matumbo-viva-universe',version:1,active:U.active,path:[...U.path],simulationClock:'Per-space clocks; inactive spaces are paused, not simulated in the background.',cameraFrames:false,worlds:[...U.worlds.values()].map(copy),events:copy(U.journal)};if(JSON.stringify(data).length>8*1024*1024)throw Error('Universe exceeds 8 MB export limit');return data;};
U.import=async function(data){editable();if(E.tape.recording||E.video)throw Error('Stop recordings before replacing the universe.');if(JSON.stringify(data).length>8*1024*1024)throw Error('Universe exceeds 8 MB');U.importing=true;try{const worlds=C.validateUniverse(data,validateState),events=C.boundedEvents(data.events||[]);for(const id of worlds.keys())for(const p of C.route(id))if(!worlds.has(p))throw Error('Missing ancestor space');const state=worlds.get(data.active).state;release();baseApply(state,false);U.worlds=worlds;templates.clear();U.active=data.active;U.path=C.route(data.active);U.journal=events;U.sequence=Math.max(0,...events.map(e=>e.sequence));U.dirty=false;refresh();tell('Universe restored. Camera stays off until explicitly started.');}finally{U.importing=false;}};
function database(){return new Promise((resolve,reject)=>{let done=false;const timer=setTimeout(()=>{done=true;reject(Error('Storage timed out; export JSON instead'));},3500);const req=indexedDB.open('matumbo-viva-universe',1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('world'))req.result.createObjectStore('world');};req.onsuccess=()=>{clearTimeout(timer);if(done){req.result.close();return;}done=true;resolve(req.result);};const fail=error=>{clearTimeout(timer);if(!done){done=true;reject(error);}};req.onerror=()=>fail(req.error);req.onblocked=()=>fail(Error('Storage is blocked by another tab'));});}
async function store(value){const db=await database();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('world',value?'readwrite':'readonly'),req=value?tx.objectStore('world').put(value,'current'):tx.objectStore('world').get('current');const timer=setTimeout(()=>{try{tx.abort();}catch(_){}reject(Error('Storage write/read timed out'));},3500);tx.oncomplete=()=>{clearTimeout(timer);resolve(req.result);};tx.onabort=()=>{clearTimeout(timer);reject(tx.error||Error('Storage cancelled'));};tx.onerror=()=>{clearTimeout(timer);reject(tx.error);};});}finally{db.close();}}
U.save=async function(){if(U.saving)return;const data=U.export();U.saving=true;try{await store(data);U.dirty=false;event('save');U.dirty=false;tell('All visited spaces saved on this browser. Export JSON for a portable copy.');}catch(e){tell('Browser storage unavailable: '+e.message+'. Export universe JSON instead.');throw e;}finally{U.saving=false;}};
U.load=async function(){editable();const data=await store();if(!data)throw Error('No Viva universe saved on this browser.');return U.import(data);};
function download(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
const style=document.createElement('style');style.textContent=`
#vivaScene{position:fixed;inset:0;width:100%;height:100%;z-index:3;pointer-events:none}#vivaBar{position:fixed;left:12px;right:12px;top:310px;z-index:19;display:flex;gap:6px;max-width:600px}#vivaBar button{min-height:43px;padding:8px 12px;background:#102b34;color:#cadfd6;border:1px solid #577f83;border-radius:9px;font:12px system-ui}#vivaBar button:first-child{background:#285548}#vivaBar button:disabled{opacity:.5}#vivaMessage{position:fixed;left:12px;right:12px;top:362px;z-index:7;font:11px/1.5 system-ui;color:#b4cec5;max-width:560px;pointer-events:none}
#vivaSpaceLabel{position:fixed;left:16px;top:20px;z-index:19;font:11px/1.45 system-ui;letter-spacing:.08em;color:#a5bbb6;display:none}#vivaSpaceLabel strong{display:block;font-size:25px;letter-spacing:-.03em;color:#d0e7db;margin-top:3px}#vivaMapDialog{width:min(610px,calc(100vw - 20px));max-height:90dvh;background:#0c2029;border:1px solid #628b84;border-radius:18px;color:#cedfd8;font:13px/1.6 system-ui}#vivaMapDialog button{min-height:44px;padding:9px 12px;margin:4px;font:12px system-ui}#vivaMap{width:100%;height:290px;touch-action:none;background:#071821;border-radius:12px}#vivaWorldList{display:flex;flex-wrap:wrap}#vivaMapDialog p{font-size:12px}
.viva-inside #vivaSpaceLabel{display:block}.viva-inside .camera-launch{top:253px;bottom:auto!important;right:12px;z-index:19}.viva-inside .brand,.viva-inside .dimensions-wrap{visibility:hidden}.viva-inside #studioBadge{display:none}.viva-inside .topbar{z-index:20}.viva-inside #toast{top:73px}.viva-inside .top-left,.viva-inside .left-head,.viva-inside .experiment,.viva-inside .top-center,.viva-inside .landmarks,.viva-inside .dimension-controls{display:none!important}.viva-inside #field{opacity:.13!important}.viva-inside .touch-state{top:92px}.viva-inside #studioOpen{top:153px!important}.viva-inside #studioBadge{top:95px!important;left:12px}.viva-inside #vivaLightOpen{top:203px!important}.viva-inside #vivaBar{top:auto;bottom:calc(254px + env(safe-area-inset-bottom))}.viva-inside #vivaMessage{top:auto;bottom:calc(304px + env(safe-area-inset-bottom));max-width:100%}.viva-inside #vivaLightHud{bottom:calc(358px + env(safe-area-inset-bottom))}.viva-inside .dimension-caption{display:none}.viva-inside #studioPad{bottom:315px}.xr-running #vivaBar,.xr-running #vivaMessage,.xr-running #vivaSpaceLabel,.xr-running #vivaScene{display:none}
@media(min-width:821px){#vivaBar{top:183px;right:auto}#vivaMessage{top:235px}.viva-inside #vivaBar{bottom:183px}.viva-inside #vivaMessage{bottom:234px}.viva-inside #vivaLightHud{bottom:288px}.viva-inside #studioOpen{right:12px;top:79px!important}.viva-inside #vivaLightOpen{top:132px!important}.viva-inside #studioBadge{left:auto;right:180px}}
@media(max-height:610px){#vivaBar{top:210px;max-width:55vw}.viva-inside #vivaBar{bottom:146px}.viva-inside #vivaMessage{bottom:195px}.viva-inside #vivaLightHud{bottom:12px}.viva-inside #studioOpen{top:55px!important}.viva-inside #vivaLightOpen{top:105px!important}}

.viva-inside.viva-focus .touch-state,.viva-inside.viva-focus .touch-bar,.viva-inside.viva-focus #studioOpen,.viva-inside.viva-focus #vivaLightOpen,.viva-inside.viva-focus .camera-launch,.viva-inside.viva-focus .bottom-center,.viva-inside.viva-focus .stats,.viva-inside.viva-focus #vivaMessage{display:none!important}
.viva-inside.viva-focus #vivaBar{bottom:calc(20px + env(safe-area-inset-bottom));top:auto;max-width:100%;right:12px}
.viva-inside.viva-focus #vivaBar button{flex:1;padding:7px 5px;font-size:11px}
.viva-inside.viva-focus #vivaLightHud{bottom:76px;left:12px;font-size:9px;padding:5px 9px}
.viva-inside.viva-focus.camera-live #vivaLightHud{bottom:235px}
.viva-inside.viva-recording #studioBadge{display:block!important;left:16px;right:auto;top:78px!important;z-index:30}
`;document.head.append(style);
document.addEventListener('click',e=>{if(U.active!=='field'&&e.target.closest('#confirmReset,#loadLocal,#importState')){e.preventDefault();e.stopImmediatePropagation();tell('Use World Eye / universe save or return Outside before replacing one field.');}},true);
const scene=document.createElement('canvas');scene.id='vivaScene';document.body.append(scene);U.canvas=scene;const sctx=scene.getContext('2d');
const bar=document.createElement('div');bar.id='vivaBar';bar.innerHTML='<button id="vivaEnter">Enter Viva</button><button id="vivaBack" disabled>Outside</button><button id="vivaOverview">World Eye</button><button id="vivaFocus">Controls</button>';document.body.append(bar);
const label=document.createElement('div');label.id='vivaSpaceLabel';document.body.append(label);const msg=document.createElement('div');msg.id='vivaMessage';msg.setAttribute('role','status');msg.textContent='One state. Connected places. Enter the circuit-derived atrium.';document.body.append(msg);
const dlg=document.createElement('dialog');dlg.id='vivaMapDialog';dlg.innerHTML='<div class="dialog-header"><h2>Viva / World Eye</h2><button id="vivaMapClose">Close</button></div><div class="dialog-content"><p id="vivaWhere"></p><label>Active spatial axes <select id="vivaSpatial" aria-label="Active spatial axes"></select></label><canvas id="vivaMap" width="528" height="512" aria-label="Circuit-derived map: select a tile then enter the atrium"></canvas><div id="vivaWorldList"></div><p>Map regions are generated from a unit-resistor network and its dual. Their areas and shared edges are validated. Tiles provide mapped entrances; they do not assert that a whole room fits inside its exterior representation.</p><button id="vivaSave">Save all visited places</button><button id="vivaLoad">Restore saved universe</button><button id="vivaExport">Export universe JSON</button><button id="vivaImport">Import universe JSON</button><input id="vivaFile" type="file" accept=".json,application/json" hidden><p>Inactive spaces pause. Nothing is uploaded or recorded automatically. Original field exports save one field; this universe export saves all visited spaces and their viewpoints. Studio history records the active space identity alongside its checkpoint.</p><p>Mapped-room prototype. No room collision/occlusion model, continuous portal walk-through, eleven-axis upgrade, new neural training or physical dark-camera verification is claimed.</p></div>';document.body.append(dlg);
$('vivaFocus').onclick=()=>{U.focus=!U.focus;refresh();};
const safe=fn=>async()=>{try{await fn();}catch(e){tell(e.message);}};$('vivaEnter').onclick=safe(()=>U.enterSelected());$('vivaBack').onclick=safe(()=>U.back());$('vivaOverview').onclick=()=>{release();drawMap();dlg.showModal();};$('vivaMapClose').onclick=()=>dlg.close();$('vivaSave').onclick=safe(()=>U.save());$('vivaLoad').onclick=safe(async()=>{if(!confirm('Replace the current visited spaces with your saved universe? Export first to keep this version.'))return;await U.load();dlg.close();});$('vivaExport').onclick=safe(()=>{download('matumbo-viva-universe.json',U.export());tell('Universe JSON exported.');});$('vivaImport').onclick=()=>$('vivaFile').click();$('vivaFile').onchange=safe(async()=>{const file=$('vivaFile').files[0];if(!file)return;try{if(file.size>8*1024*1024)throw Error('Universe file exceeds 8 MB');const data=JSON.parse(await file.text());if(!confirm('Replace the current universe with this file?'))return;await U.import(data);dlg.close();}finally{$('vivaFile').value='';}});
const dimSelect=$('vivaSpatial');for(let d=2;d<=9;d++){const o=document.createElement('option');o.value=d;o.textContent=d+' space axes + time';dimSelect.append(o);}dimSelect.onchange=safe(()=>{editable();release();A.setDimensions(+dimSelect.value);U.dirty=true;N.refresh();tell(dimSelect.value+' spatial axes now affect this space; time remains separate.');});
function refresh(){document.body.classList.toggle('viva-focus',U.focus&&U.active!=='field');$('vivaFocus').textContent=U.focus?'Controls':'Focus view';dimSelect.value=String(A.engine.activeDimensions);document.body.classList.toggle('viva-inside',U.active!=='field');label.replaceChildren(document.createTextNode('VIVA / '+(U.active==='circuit'?'CIRCUIT GEOMETRY':'MAPPED INNER SPACE')));const strong=document.createElement('strong');strong.textContent=names[U.active];label.append(strong);$('vivaEnter').textContent=U.active==='field'?'Enter Viva':'Enter selected';$('vivaBack').disabled=U.active==='field';$('vivaWhere').textContent=[...C.route(U.active),U.active].map(x=>names[x]).join(' / ');document.title='maTumbo Viva · '+names[U.active];$('vivaWorldList').replaceChildren();for(const id of U.worlds.keys()){const span=document.createElement('span');span.textContent=names[id]+(id===U.active?' [HERE]':'')+' · ';$('vivaWorldList').append(span);}drawMap();}
function drawMap(){const c=$('vivaMap'),ctx=c.getContext('2d'),w=c.width,h=c.height,k=Math.min((w-30)/U.circuit.width,(h-30)/U.circuit.height);ctx.fillStyle='#071821';ctx.fillRect(0,0,w,h);const colors=['#245c65','#385e56','#355271','#5a4d63','#455f49','#685d42','#3b6269','#6c4945','#4a5268'];U.circuit.tiles.forEach((t,i)=>{const x=15+t.x*k,y=15+t.y*k;ctx.fillStyle=colors[i];ctx.fillRect(x,y,t.width*k,t.height*k);ctx.strokeStyle=i===U.selection?'#dfc99d':'#8eb1a5';ctx.lineWidth=i===U.selection?4:1;ctx.strokeRect(x,y,t.width*k,t.height*k);if(t.width>2){ctx.fillStyle='#d1e2d6';ctx.font='16px system-ui';ctx.fillText(t.id,x+7,y+21);ctx.font='12px system-ui';ctx.fillText(Math.round(t.width)+' × '+Math.round(t.height),x+7,y+39);}});}
$('vivaMap').onpointerdown=e=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*528,y=(e.clientY-r.top)/r.height*512,k=Math.min(498/U.circuit.width,482/U.circuit.height);const i=U.circuit.tiles.findIndex(t=>x>=15+t.x*k&&x<=15+(t.x+t.width)*k&&y>=15+t.y*k&&y<=15+(t.y+t.height)*k);if(i>=0){U.selection=i;if(U.active==='circuit')R.selected=i;drawMap();tell('Selected '+names['room-S'+(i+1)]+'. Close the Eye and choose Enter selected in the atrium.');}};
// Selection remains the original node selection; hidden decorative nodes do not steal touches.
const hit=N.hit.bind(N);N.hit=function(x,y,radius=24){if(U.active==='field')return hit(x,y,radius);let best=-1,dist=Math.max(radius,30);for(const l of A.landmarks){const p=R.nodeScreen[l.node];if(p?.visible){const d=Math.hypot(p.x-x,p.y-y);if(d<dist){best=l.node;dist=d;}}}return best;};
const oldDouble=N.enter.bind(N);N.enter=function(node){if(U.active==='circuit'&&node<9){R.selected=node;return U.enterSelected();}if(U.active==='room-S1'&&node===2){R.selected=node;return U.enterSelected();}return oldDouble(node);};
const drawColors=['#32666c','#466b57','#4a5e7d','#675975','#5d6a4c','#7b6b47','#427176','#795751','#596179'];
function projected(q){const b=N.projectionBasis(),p=NavMath.project(q,0,b,N.origin);return R.project(...p);}
function local3(x,y,z){const q=Array(9).fill(0);q[0]=x;q[1]=y;q[2]=z;return projected(q);}
function poly(ctx,points,fill,stroke='#608781',alpha=1){if(points.some(p=>!(p.w>.05)||!Number.isFinite(p.x)))return;ctx.save();ctx.globalAlpha*=alpha;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke();}ctx.restore();}
function cube(ctx,q,size,color){const verts=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]].map(v=>{const a=q.slice();for(let d=0;d<3;d++)a[d]+=v[d]*size;return projected(a);});const faces=[[0,1,2,3],[4,5,6,7],[0,4,7,3],[1,5,6,2],[3,2,6,7],[0,1,5,4]].map(ids=>({ids,depth:ids.reduce((s,i)=>s+(verts[i].w||0),0)/4})).sort((a,b)=>b.depth-a.depth);for(const f of faces)poly(ctx,f.ids.map(i=>verts[i]),color,'#9bb7a1',.84);}
function preview(ctx,q,childId){const world=obtain(childId),state=world.state;const small=.18;for(const node of [0,1,2,3]){const target=q.slice();for(let d=0;d<3;d++)target[d]+=state.engine.q[node*9+d]*small;target[1]+=.5;cube(ctx,target,.055,drawColors[node]);}const p=projected(q);if(p.visible){ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillStyle='#b0c9ba';ctx.fillText('LIVE STATE / ENTER',p.x,p.y-42);}}
function drawScene(ctx,w,h){if(U.active==='field')return;ctx.save();const mode=A.visibility?.effective||'balanced';const alpha=mode==='dark'?.75:1;ctx.globalAlpha=alpha;
 if(U.active==='circuit'){U.circuit.tiles.forEach((t,i)=>{const x=(t.x-U.circuit.width/2)/3,z=(t.y-U.circuit.height/2)/3,s=t.width/3;poly(ctx,[local3(x,-.62,z),local3(x+s,-.62,z),local3(x+s,-.62,z+s),local3(x,-.62,z+s)],drawColors[i],'#8aac9b',.72);});}
 else{poly(ctx,[local3(-4,-.7,-4),local3(4,-.7,-4),local3(4,-.7,4),local3(-4,-.7,4)],'#1d383b','#769d87',.8);for(let i=-4;i<=4;i++){for(const ends of [[[-4,-.695,i],[4,-.695,i]],[[i,-.695,-4],[i,-.695,4]]]){const p=ends.map(x=>local3(...x));if(p.every(p=>p.w>.05)){ctx.beginPath();ctx.moveTo(p[0].x,p[0].y);ctx.lineTo(p[1].x,p[1].y);ctx.strokeStyle='#385756';ctx.lineWidth=.6;ctx.stroke();}}}poly(ctx,[local3(-4,-.7,-4),local3(4,-.7,-4),local3(4,2.6,-4),local3(-4,2.6,-4)],'#12292e','#567a74',.7);}
 const entities=A.landmarks.map(l=>({l,q:Array.from(A.engine.q.slice(l.node*9,l.node*9+9))})).sort((a,b)=>(projected(b.q).w||0)-(projected(a.q).w||0));for(const {l,q}of entities){const isPortal=U.active==='circuit'||U.active==='room-S1'&&l.node===2;const size=isPortal?.28:.22;cube(ctx,q,size,drawColors[l.node%9]);if(R.selected===l.node&&isPortal)preview(ctx,q,U.active==='circuit'?'room-S'+(l.node+1):'inner-lab');}ctx.restore();}
U.drawScene=drawScene;
U.drawCapture=function(ctx,w,h){if(U.active==='field')return;ctx.save();ctx.scale(w/R.width,h/R.height);drawScene(ctx,R.width,R.height);ctx.restore();U.captureDraws++;};
const render=R.render.bind(R);let lastMoveCount=0;R.render=function(dt){render(dt);document.body.classList.toggle('viva-recording',!!E.video||E.tape.recording);if(!P.stream&&$('touchStatus')?.textContent.includes('Hand lost'))$('touchStatus').textContent='TOUCH READY · drag a handle';const dpr=Math.min(devicePixelRatio||1,1.25),w=R.width,h=R.height;if(scene.width!==Math.round(w*dpr)||scene.height!==Math.round(h*dpr)){scene.width=Math.round(w*dpr);scene.height=Math.round(h*dpr);}sctx.setTransform(dpr,0,0,dpr,0,0);sctx.clearRect(0,0,w,h);drawScene(sctx,w,h);if(T.moves!==lastMoveCount){lastMoveCount=T.moves;U.dirty=true;}if(U.active==='circuit')U.selection=Math.min(8,R.selected);};
const historyImport=E.importHistory.bind(E);E.importHistory=async data=>{if(Array.isArray(data?.frames))for(const frame of data.frames)if(frame.state?.viva&&!C.validMeta(frame.state.viva))throw Error('History has invalid space metadata');return historyImport(data);};
// Preserve universe identity when explicit state reset is requested through public API.
const reset=A.resetNow.bind(A);A.resetNow=function(){editable();if(U.active!=='field')throw Error('Leave mapped spaces before resetting the original field');return reset();};
const xrStart=A.xr.start.bind(A.xr);A.xr.start=async function(){if(U.active!=='field'){tell('Return Outside to the original field for Room AR. These interiors are mapped spaces, not room anchors.');return false;}return xrStart();};
const diag=P.diagnostics.bind(P);P.diagnostics=function(){const d=diag();d.viva={version:U.version,activeSpace:U.active,path:U.path,visited:U.worlds.size,dirty:U.dirty,circuitResidual:U.circuit.residual,cameraRegistration:'overlay only for mapped interiors',inactiveClocks:'paused',drawsIncludedInCapture:U.captureDraws};$('diagnosticsText').textContent=JSON.stringify(d,null,2);return d;};
stash();refresh();
})();
