/* Dependency-free regression checks for the additive repair. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const context={module:{exports:{}}};vm.runInNewContext(fs.readFileSync('src/field-lab/field-lab-touch-repair.js','utf8'),context);const m=context.module.exports;let passed=0;
const check=(name,fn)=>{fn();passed++;console.log('PASS',name);};
for(let d=2;d<=9;d++)check(d+'D dragging projects correctly and preserves dormant coordinates',()=>{const b=Array.from({length:3},(_,i)=>Array.from({length:9},(_,j)=>j>=d?0:i===j?1:j>=3?.2*Math.sin(i+j+1):0));if(d===2)b[2].fill(0);const matrix=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];const delta=m.screenDelta(b,matrix,[0,0,0],30,-20,300,400,d);assert(Math.abs(b[0].reduce((s,v,j)=>s+v*delta[j],0)-.2)<1e-10);assert(Math.abs(b[1].reduce((s,v,j)=>s+v*delta[j],0)-.1)<1e-10);for(let j=d;j<9;j++)assert.equal(delta[j],0);});
check('Pinch calibration is ordered and rejects overlapping classes',()=>{assert(m.validProfile(m.calibrate(Array(24).fill(1.1),Array(24).fill(.12))));assert.throws(()=>m.calibrate(Array(24).fill(.2),Array(24).fill(.2)));assert(!m.validProfile({version:1,close:NaN,open:.4}));});
check('Filter accepts fast movement and resets after a tracking gap',()=>{const f=new m.OneEuro();f.update(0,0);for(let t=16;t<=160;t+=16)f.update(1,t);assert(f.x>.8);assert.equal(f.update(.4,1000),.4);});
for(const dim of [2,3,9])check('Cached contact candidates preserve exact '+dim+'D contacts',()=>{const e={q:Float64Array.from({length:90*9},(_,i)=>Math.sin(i*2.13)),count:90,activeDimensions:dim,law:{radius:.7,contact:1}};for(let step=0;step<16;step++){e.q[(step*11)%e.q.length]+=.12;const cached=[],exact=[];m.contacts.call(e,(a,b,r)=>cached.push([a,b,r]));for(let a=0;a<e.count;a++)for(let b=a+1;b<e.count;b++){let r=0;for(let k=0;k<dim;k++)r+=(e.q[b*9+k]-e.q[a*9+k])**2;if(r<(2*e.law.radius)**2)exact.push([a,b,Math.sqrt(r)]);}assert.deepEqual(cached,exact);}});
console.log(JSON.stringify({passed,physicalPhoneTest:false}));
